// Dados de criação de personagem resumidos das Basic Rules de D&D 5e (2014).
// Cada grupo de equipamento permite escolher uma alternativa; os itens fixos vêm à parte.
const regrasClasse = {
 'Bárbaro': {armaduras:'Leves, médias e escudos',armas:'Simples e marciais',ferramentas:'Nenhuma',resistencias:['Força','Constituição'],quantidade:2,pericias:['Adestrar Animais','Atletismo','Intimidação','Natureza','Percepção','Sobrevivência'],grupos:[['Machado grande','Arma marcial corpo a corpo à escolha'],['Dois machados de mão','Arma simples à escolha']],fixos:['Mochila de explorador','Quatro azagaias']},
 'Bardo': {armaduras:'Leves',armas:'Simples, besta de mão, espada longa, rapieira e espada curta',ferramentas:'Três instrumentos musicais à escolha',resistencias:['Destreza','Carisma'],quantidade:3,pericias:['Acrobacia','Adestrar Animais','Arcanismo','Atletismo','Atuação','Enganação','Furtividade','História','Intimidação','Intuição','Investigação','Medicina','Natureza','Percepção','Persuasão','Prestidigitação','Religião','Sobrevivência'],grupos:[['Rapieira','Espada longa','Arma simples à escolha'],['Mochila de diplomata','Mochila de artista'],['Alaúde','Instrumento musical à escolha']],fixos:['Armadura de couro','Adaga']},
 'Clérigo': {armaduras:'Leves, médias e escudos; domínio pode ampliar',armas:'Simples; domínio pode ampliar',ferramentas:'Nenhuma',resistencias:['Sabedoria','Carisma'],quantidade:2,pericias:['História','Intuição','Medicina','Persuasão','Religião'],grupos:[['Maça','Martelo de guerra (se proficiente)'],['Cota de escamas','Armadura de couro','Cota de malha (se proficiente)'],['Besta leve e 20 virotes','Arma simples à escolha'],['Mochila de sacerdote','Mochila de explorador']],fixos:['Escudo','Símbolo sagrado']},
 'Druida': {armaduras:'Leves, médias e escudos; não usa metal',armas:'Clava, adaga, dardo, azagaia, maça, bordão, cimitarra, foice, funda e lança',ferramentas:'Kit de herbalismo',resistencias:['Inteligência','Sabedoria'],quantidade:2,pericias:['Arcanismo','Adestrar Animais','Intuição','Medicina','Natureza','Percepção','Religião','Sobrevivência'],grupos:[['Escudo de madeira','Arma simples à escolha'],['Cimitarra','Arma simples corpo a corpo à escolha']],fixos:['Armadura de couro','Mochila de explorador','Foco druídico']},
 'Guerreiro': {armaduras:'Todas e escudos',armas:'Simples e marciais',ferramentas:'Nenhuma',resistencias:['Força','Constituição'],quantidade:2,pericias:['Acrobacia','Adestrar Animais','Atletismo','História','Intimidação','Intuição','Percepção','Sobrevivência'],grupos:[['Cota de malha','Armadura de couro, arco longo e 20 flechas'],['Arma marcial à escolha e escudo','Duas armas marciais à escolha'],['Besta leve e 20 virotes','Dois machados de mão'],['Mochila de explorador de masmorras','Mochila de explorador']],fixos:[]},
 'Monge': {armaduras:'Nenhuma',armas:'Simples e espadas curtas',ferramentas:'Um tipo de ferramenta de artesão ou instrumento musical',resistencias:['Força','Destreza'],quantidade:2,pericias:['Acrobacia','Atletismo','História','Intuição','Religião','Furtividade'],grupos:[['Espada curta','Arma simples à escolha'],['Mochila de explorador de masmorras','Mochila de explorador']],fixos:['Dez dardos']},
 'Paladino': {armaduras:'Todas e escudos',armas:'Simples e marciais',ferramentas:'Nenhuma',resistencias:['Sabedoria','Carisma'],quantidade:2,pericias:['Atletismo','Intuição','Intimidação','Medicina','Persuasão','Religião'],grupos:[['Arma marcial à escolha e escudo','Duas armas marciais à escolha'],['Cinco azagaias','Arma simples corpo a corpo à escolha'],['Mochila de sacerdote','Mochila de explorador']],fixos:['Cota de malha','Símbolo sagrado']},
 'Patrulheiro': {armaduras:'Leves, médias e escudos',armas:'Simples e marciais',ferramentas:'Nenhuma',resistencias:['Força','Destreza'],quantidade:3,pericias:['Adestrar Animais','Atletismo','Intuição','Investigação','Natureza','Percepção','Furtividade','Sobrevivência'],grupos:[['Cota de escamas','Armadura de couro'],['Duas espadas curtas','Duas armas simples corpo a corpo à escolha'],['Mochila de explorador de masmorras','Mochila de explorador']],fixos:['Arco longo e aljava com 20 flechas']},
 'Ladino': {armaduras:'Leves',armas:'Simples, besta de mão, espada longa, rapieira e espada curta',ferramentas:'Ferramentas de ladrão',resistencias:['Destreza','Inteligência'],quantidade:4,pericias:['Acrobacia','Atletismo','Enganação','Intuição','Intimidação','Investigação','Percepção','Atuação','Persuasão','Prestidigitação','Furtividade'],grupos:[['Rapieira','Espada curta'],['Arco curto e aljava com 20 flechas','Espada curta'],['Mochila de assaltante','Mochila de explorador de masmorras','Mochila de explorador']],fixos:['Armadura de couro','Duas adagas','Ferramentas de ladrão']},
 'Feiticeiro': {armaduras:'Nenhuma',armas:'Adaga, dardo, funda, bordão e besta leve',ferramentas:'Nenhuma',resistencias:['Constituição','Carisma'],quantidade:2,pericias:['Arcanismo','Enganação','Intuição','Intimidação','Persuasão','Religião'],grupos:[['Besta leve e 20 virotes','Arma simples à escolha'],['Bolsa de componentes','Foco arcano'],['Mochila de explorador de masmorras','Mochila de explorador']],fixos:['Duas adagas']},
 'Bruxo': {armaduras:'Leves',armas:'Simples',ferramentas:'Nenhuma',resistencias:['Sabedoria','Carisma'],quantidade:2,pericias:['Arcanismo','Enganação','História','Intimidação','Investigação','Natureza','Religião'],grupos:[['Besta leve e 20 virotes','Arma simples à escolha'],['Bolsa de componentes','Foco arcano'],['Mochila de estudioso','Mochila de explorador de masmorras']],fixos:['Armadura de couro','Arma simples à escolha','Duas adagas']},
 'Mago': {armaduras:'Nenhuma',armas:'Adaga, dardo, funda, bordão e besta leve',ferramentas:'Nenhuma',resistencias:['Inteligência','Sabedoria'],quantidade:2,pericias:['Arcanismo','História','Intuição','Investigação','Medicina','Religião'],grupos:[['Bordão','Adaga'],['Bolsa de componentes','Foco arcano'],['Mochila de estudioso','Mochila de explorador']],fixos:['Livro de magias']}
};
const detalhesRaca = {
 'Humano':{tamanho:'Médio',deslocamento:'9 m',idiomas:'Comum e um idioma à escolha',tracos:['Versátil entre culturas e tradições.','Na opção padrão, todos os seis atributos recebem +1.','Não possui visão no escuro pela raça.'],nota:'A variante humana é uma regra opcional separada.'},
 'Elfo':{tamanho:'Médio',deslocamento:'9 m',idiomas:'Comum e Élfico',tracos:['Destreza +2 e visão no escuro de 18 m.','Sentidos Aguçados concede proficiência em Percepção.','Ancestralidade Feérica ajuda contra encantamento; Transe substitui o sono comum.'],nota:'Alto elfo, elfo da floresta e drow têm traços adicionais diferentes.'},
 'Anão':{tamanho:'Médio',deslocamento:'7,5 m',idiomas:'Comum e Anão',tracos:['Constituição +2 e visão no escuro de 18 m.','Resiliência Anã dá vantagem contra veneno e resistência a dano de veneno.','Treinamento com machados e martelos e aptidão com ferramentas de artesão.'],nota:'Anão da colina e da montanha acrescentam benefícios próprios.'},
 'Halfling':{tamanho:'Pequeno',deslocamento:'7,5 m',idiomas:'Comum e Halfling',tracos:['Destreza +2.','Sorte permite repetir um 1 natural em teste, ataque ou resistência.','Bravura melhora resistências contra medo e Agilidade Halfling facilita passar por criaturas maiores.'],nota:'Pés-leves e robustos possuem traços adicionais.'},
 'Draconato':{tamanho:'Médio',deslocamento:'9 m',idiomas:'Comum e Dracônico',tracos:['Força +2 e Carisma +1.','A ancestralidade dracônica determina o tipo da arma de sopro e da resistência a dano.','A arma de sopro possui uso limitado entre descansos.'],nota:'Escolha a cor ou metal da ancestralidade para definir tipo de dano e formato do sopro.'},
 'Gnomo':{tamanho:'Pequeno',deslocamento:'7,5 m',idiomas:'Comum e Gnômico',tracos:['Inteligência +2 e visão no escuro de 18 m.','Astúcia Gnômica dá vantagem em resistências mentais contra magia.','Curiosidade e inventividade fazem parte da identidade gnômica.'],nota:'Gnomo da floresta e das rochas têm traços adicionais diferentes.'},
 'Meio-elfo':{tamanho:'Médio',deslocamento:'9 m',idiomas:'Comum, Élfico e um idioma à escolha',tracos:['Carisma +2 e outros dois atributos à escolha recebem +1.','Visão no escuro de 18 m e Ancestralidade Feérica.','Versatilidade em Perícias concede duas proficiências à escolha.'],nota:'As duas perícias raciais são adicionais às escolhas de classe.'},
 'Meio-orc':{tamanho:'Médio',deslocamento:'9 m',idiomas:'Comum e Orc',tracos:['Força +2 e Constituição +1.','Visão no escuro de 18 m e proficiência em Intimidação.','Resistência Implacável evita cair a 0 PV uma vez por descanso longo; Ataques Selvagens fortalece críticos corpo a corpo.'],nota:'A Resistência Implacável não substitui todas as condições de morte instantânea.'},
 'Tiefling':{tamanho:'Médio',deslocamento:'9 m',idiomas:'Comum e Infernal',tracos:['Carisma +2 e Inteligência +1.','Visão no escuro de 18 m e resistência a dano de fogo.','Legado Infernal concede truques e magias conforme o nível.'],nota:'A magia racial utiliza Carisma como atributo de conjuração.'}
};
